/**
 * nav.js — Custom Kicks
 * Generated by UI/UX Designer (Agent 3) — 2026-03-10
 *
 * Responsibilities:
 * 1. Mobile nav toggle (hamburger opens/closes .nav-menu via .nav-open on body)
 * 2. Copyright year — sets #copyright-year text content from current year
 * 3. IntersectionObserver — adds .is-visible to .section-animate elements on viewport entry
 *
 * Deferred via `defer` attribute on all pages. No inline scripts needed.
 */

(function () {
  'use strict';

  /* ------------------------------------------------------------------
     1. MOBILE NAV TOGGLE
     Toggles .nav-open class on <body>. Hamburger animates to X via CSS.
     Updates aria-expanded on the hamburger button.
  ------------------------------------------------------------------ */

  var hamburger = document.querySelector('.hamburger');
  var navMenu = document.getElementById('nav-menu');

  if (hamburger && navMenu) {

    // Create overlay element to dismiss menu on outside click
    var overlay = document.createElement('div');
    overlay.className = 'nav-overlay';
    overlay.setAttribute('aria-hidden', 'true');
    document.body.appendChild(overlay);

    function openNav() {
      document.body.classList.add('nav-open');
      hamburger.setAttribute('aria-expanded', 'true');
      hamburger.setAttribute('aria-label', 'Close navigation menu');
    }

    function closeNav() {
      document.body.classList.remove('nav-open');
      hamburger.setAttribute('aria-expanded', 'false');
      hamburger.setAttribute('aria-label', 'Open navigation menu');
    }

    function toggleNav() {
      if (document.body.classList.contains('nav-open')) {
        closeNav();
      } else {
        openNav();
      }
    }

    hamburger.addEventListener('click', toggleNav);

    // Close menu when clicking the overlay
    overlay.addEventListener('click', closeNav);

    // Close menu on Escape key
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && document.body.classList.contains('nav-open')) {
        closeNav();
        hamburger.focus();
      }
    });

    // Close menu when a nav link is clicked (single-page navigation / internal links)
    var navLinks = navMenu.querySelectorAll('.nav-link, .nav-cta');
    navLinks.forEach(function (link) {
      link.addEventListener('click', function () {
        if (document.body.classList.contains('nav-open')) {
          closeNav();
        }
      });
    });

    // Close mobile nav when viewport resizes to desktop width
    var mobileBreakpoint = 769;
    window.addEventListener('resize', function () {
      if (window.innerWidth >= mobileBreakpoint && document.body.classList.contains('nav-open')) {
        closeNav();
      }
    });
  }


  /* ------------------------------------------------------------------
     2. COPYRIGHT YEAR
     Sets the text content of #copyright-year to the current year.
     No inline scripts needed in HTML.
  ------------------------------------------------------------------ */

  var yearEl = document.getElementById('copyright-year');
  if (yearEl) {
    yearEl.textContent = new Date().getFullYear();
  }


  /* ------------------------------------------------------------------
     3. SECTION ENTRANCE ANIMATIONS — IntersectionObserver
     Observes all .section-animate elements.
     Adds .is-visible class when the element enters the viewport.
     Unobserves each element after it has triggered once.

     Committed motion moments (section entrance):
     - First content section below hero
     - Trust bar
     - How It Works blocks
     - Featured drops grid
     These sections receive class="section-animate" in page HTML.
  ------------------------------------------------------------------ */

  // Respect prefers-reduced-motion — do not observe if motion is reduced
  var prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)');

  if (!prefersReducedMotion.matches && 'IntersectionObserver' in window) {

    var sectionObserver = new IntersectionObserver(
      function (entries, observer) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add('is-visible');
            observer.unobserve(entry.target); // Fire once, then stop observing
          }
        });
      },
      {
        threshold: 0.1,       // Trigger when 10% of the element is visible
        rootMargin: '0px 0px -40px 0px' // Slightly before the very bottom of viewport
      }
    );

    var animatedSections = document.querySelectorAll('.section-animate');
    animatedSections.forEach(function (section) {
      sectionObserver.observe(section);
    });

  } else {
    // If reduced motion or no IntersectionObserver support, make all elements visible immediately
    var sectionsToShow = document.querySelectorAll('.section-animate');
    sectionsToShow.forEach(function (section) {
      section.classList.add('is-visible');
    });
  }


  /* ------------------------------------------------------------------
     4. HERO ENTRANCE ANIMATION — index.html only
     Staggered fade-up: H1 → subhead → CTA
     Elements need class="hero-animate" in HTML.
     Delay classes: (none = 0ms), hero-animate--delay-1 (150ms), hero-animate--delay-2 (300ms)
     This function adds .hero-visible on DOM ready to trigger the CSS animation.
  ------------------------------------------------------------------ */

  if (!prefersReducedMotion.matches) {
    var heroElements = document.querySelectorAll('.hero-animate');
    if (heroElements.length > 0) {
      // Small rAF delay ensures the browser has painted the initial invisible state
      requestAnimationFrame(function () {
        requestAnimationFrame(function () {
          heroElements.forEach(function (el) {
            el.classList.add('hero-visible');
          });
        });
      });
    }
  } else {
    // Reduced motion — make hero elements immediately visible
    var heroEls = document.querySelectorAll('.hero-animate');
    heroEls.forEach(function (el) {
      el.classList.add('hero-visible');
    });
  }

})();
